In [2]:
import numpy as np

In [4]:
temperature_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
temperature_w1

array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

In [6]:
print("shape :", temperature_w1.shape)
print("Data Type :", temperature_w1.dtype)
print("Number of Elements :", temperature_w1.size)


shape : (7,)
Data Type : float64
Number of Elements : 7


In [9]:
fahrenheit = (temperature_w1 * 9/5) + 32

print("Fahrenheit temperatures:", fahrenheit)

print("Maximum temperature:", temperature_w1.max())

print("Minimum temperature:", temperature_w1.min())

print("Mean temperature:", temperature_w1.mean())

Fahrenheit temperatures: [72.5  77.54 69.44 74.12 78.98 76.64 71.42]
Maximum temperature: 26.1
Minimum temperature: 20.8
Mean temperature: 23.542857142857144


In [10]:
print("First three days:", temperature_w1[:3])

print("Weekend:", temperature_w1[-2:])

print("Middle three days:", temperature_w1[2:5])

First three days: [22.5 25.3 20.8]
Weekend: [24.8 21.9]
Middle three days: [20.8 23.4 26.1]


In [11]:
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
])

print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


In [12]:
print("Shape:", temperatures.shape)
print("Data Type:", temperatures.dtype)
print("Total Number of Elements:", temperatures.size)

Shape: (2, 7)
Data Type: float64
Total Number of Elements: 14


In [13]:
print("Week 1:", temperatures[0])
print("Week 2:", temperatures[1])

print("Week 1 Weekend:", temperatures[0, -2:])
print("Week 2 Weekend:", temperatures[1, -2:])

Week 1: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Week 2: [19.2 22.5 21.3 24.  23.5 22.8 20.1]
Week 1 Weekend: [24.8 21.9]
Week 2 Weekend: [22.8 20.1]


In [14]:
import pandas as pd

marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=["Rank1", "Rank2", "Rank3", "Rank4", "Rank5"]
)

print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [15]:
print("1st Rank Mark:", marks.iloc[0])

print("Top 3 Ranks:")
print(marks.loc[["Rank1", "Rank2", "Rank3"]])

print("3rd Rank Mark:", marks.iloc[2])

print("Marks greater than 90:")
print(marks[marks > 90])

1st Rank Mark: 95
Top 3 Ranks:
Rank1    95
Rank2    92
Rank3    89
dtype: int64
3rd Rank Mark: 89
Marks greater than 90:
Rank1    95
Rank2    92
dtype: int64


In [16]:
marks.loc["Rank1"] = 100

marks = marks.drop("Rank5")

cgpa = marks / 10

print("Updated Marks:")
print(marks)

print("CGPA:")
print(cgpa)

Updated Marks:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64
CGPA:
Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


In [17]:
import pandas as pd

transactions = pd.DataFrame({
    "TransactionID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    
    "ProductCategory": [
        "Electronics", "Clothing", "Electronics", "Furniture", "Clothing",
        "Electronics", "Furniture", "Clothing", "Furniture", "Electronics"
    ],
    
    "Region": [
        "North", "South", "North", "East", "West",
        "North", "East", "West", "South", "North"
    ],
    
    "Amount": [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [18]:
print(transactions)

print("Shape:", transactions.shape)
print("Column Names:", transactions.columns)
print("Data Types:")
print(transactions.dtypes)

print("Head:")
print(transactions.head())

print("Tail:")
print(transactions.tail())

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400
Shape: (10, 4)
Column Names: Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='str')
Data Types:
TransactionID      int64
ProductCategory      str
Region               str
Amount             int64
dtype: object
Head:
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East   

In [19]:
print(transactions[["ProductCategory", "Amount"]])

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400


In [20]:
print(transactions.iloc[:, -3:])

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400


In [21]:
print(transactions[
    (transactions["Region"] == "North") &
    (transactions["Amount"] > 200)
])

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400


In [22]:
print(transactions["ProductCategory"].value_counts())

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64


In [23]:
print(transactions["Region"].unique())

<ArrowStringArray>
['North', 'South', 'East', 'West']
Length: 4, dtype: str


In [24]:
print(transactions.groupby("Region")["Amount"].mean())

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64


In [25]:
transactions.loc[transactions["TransactionID"] == 102, "Amount"] = 165

transactions["Discount"] = transactions["Amount"] * 0.10

transactions = transactions[transactions["TransactionID"] != 109]

transactions = transactions.drop(columns=["Discount"])

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400
